server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

mybatis:
  type-handlers-package: com.ryo.mybatisdemo.springbootmybatis.typehandler
  mapper-locations: classpath:mapping/*.xml
